### ISSUE TITLE
どう作るか

### ISSUE THREAD

**Issue by kut-arika** [superwower/wowgit#1]
- [x] gitクライアントにどういう機能持たせるか
- [x] アーキテクチャ（使う技術スタック）
  - [x] 使うライブラリ
    - https://github.com/nodegit/nodegit
    - https://github.com/isomorphic-git/isomorphic-git
    - https://github.com/steveukx/git-js

**Comment by hitochan777** [comment]
https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html
機能としてはまずは基本的なところから初めるのはどうでしょう？
あとコミットグラフを可視化する機能もほしいですね。

**Comment by kut-arika** [comment]
## 機能
目指すところはどこだろう？Sourcetree？
https://ja.atlassian.com/software/sourcetree

## アーキ
上のライブラリを見る感じ、nodeで作るのかな。
Vueはちょっとふれたので、Angular6かReactがいいなぁ。
もちろんVueでもいいです。

**Comment by kut-arika** [comment]
基本機能については同意です
- git clone
- git branch
- git checkout
- git add / reset (stage / unstage)
- git diff
- git commit
- git push
- git pull / fetch

**Comment by hitochan777** [comment]
個人的には結構気に入ってるungitのUIをもっと改善した形にしたいです。
例えばコミットログをみるのにノードをクリックしないといけないし、一つのログしか見れなかったはずです。
なので、`git log --oneline --graph`みたいに簡潔にグラフ表示できると嬉しいとか思ってます。

**Comment by kut-arika** [comment]
了解す！
https://github.com/FredrikNoren/ungit

**Comment by hitochan777** [comment]
# 技術
- Client: Vue.js, React, Angular, Hyperapp, Elm (Hyperappはライトウェイトで素敵だと思ってます！)
- Backend: [ここ](https://github.com/libgit2/libgit2#language-bindings)に上がってるもので、gitコマンドでできることがほとんど実現できるものならなんでもいいと思います！

**Comment by kut-arika** [comment]
えいやで決めてもらっておけ。

**Comment by hitochan777** [comment]
使用技術は以下で決定
- フロント: React
- バックエンド
  - サーバーフレームワーク: [Loopback](https://loopback.io/)(Node.js)
  - ライブラリ
      - Nodegit: node.jsでgit操作をするためのライブラリ

**Comment by hitochan777** [comment]
[fastify](https://github.com/fastify/fastify)でもいい気がしてきた。

**Comment by kut-arika** [comment]
ええで！

**Comment by hitochan777** [comment]
サーバーフレームワークはfastifyで行きましょう！
サーバーの問題かどうかはわからないですが、ungitは処理がおそすぎてイライラするので
パフォーマンスは重要かと。
