### ISSUE TITLE
git push 時の husky でのチェックをなくす

### ISSUE THREAD

**Issue by kut-arika** [superwower/wowgit#37]
commit 時にチェックして入れば push するときに変なものは入らないはずなのでpush時のチェックは不要。

**Comment by hitochan777** [comment]
rebaseするときはcommit hookは走らないので、testが通らないものがpushされてしまうという可能性があることに気づきました。
pre-rebaseというのもあるみたいなので、push時のチェックを消してre-rebaseで代わりにやればいいかもしれないですね。
