### ISSUE TITLE
コードフォーマッター設定

### ISSUE THREAD

**Issue by hitochan777** [superwower/wowgit#5]
Prettierというフォーマッターを適用できるようにする

- [x] package.jsonにscriptsとしてformatを追加
- [x] prettierの設定をpackage.jsonか.prettierrcに書く
- [x] prettierを使っているというのを示すためにバッジをREADMEに追加

**Comment by yniu999** [comment]
オプションはどんなのつけたら良いでしょう？
ひとまず
```
printWidth: 100
tabWidth: 2
singleQuote: true
```
あたりかなと思ったのですが

**Comment by hitochan777** [comment]
基本的にデフォルトでいいと思います。
