### ISSUE TITLE
Typescriptが使えるようにする

### ISSUE THREAD

**Issue by hitochan777** [superwower/wowgit#8]

**Comment by kut-arika** [comment]
https://qiita.com/biga816/items/92d8537a34ebe0f70152
gulpはいやよね。

**Comment by kut-arika** [comment]
https://www.fastify.io/docs/master/TypeScript/
こっちか

**Comment by hitochan777** [comment]
webpackかparcelとかのほうがいいですかね...

**Comment by hitochan777** [comment]
#9 も一緒にやることになると思うので、今出してるPRがマージされたら#9もcloseしてください〜
